{% set name = "scikit-build-core" %}
{% set version = "0.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scikit_build_core-{{ version }}.tar.gz
  sha256: 04cbb59fe795202a7eeede1849112ee9dcbf3469feebd9b8b36aa541336ac4f8

build:
  noarch: python
  number: 1

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - exceptiongroup >=1.0
    - importlib-metadata >=4.13
    - importlib-resources >=1.3
    - packaging >=21.3
    - pathspec >=0.10.1
    - tomli >=1.2.2
    - typing-extensions >=3.10

test:
  imports:
    - scikit_build_core
  commands:
    - pip check
    - pytest -vv -m "not isolated" -k "not sdist_time_hash_set_epoch and not sdist_hash"
  source_files:
    - tests/
    - src/
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python-build
    - cattrs >=22.2
    - cmake
    - hatch-vcs
    - hatchling
    - make
    - ninja
    - pip
    - pybind11
    - pytest >=7.0
    - pytest-subprocess
    - rich
    - setuptools
    - virtualenv
    - wheel
    - python {{ python_min }}

about:
  home: https://pypi.org/project/scikit-build-core/
  summary: Build backend for CMake based projects
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/scikit_build_core/resources/find_python/Copyright.txt

extra:
  recipe-maintainers:
    - conda-forge/scikit-build
    - henryiii
    - jcfr
    - thewtex
