schema_version: 1

context:
  name: scikit-build-core
  version: 0.12.1
  python_min: '3.8'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/scikit_build_core-${{ version }}.tar.gz
  sha256: bb663e71116bcd23d208ef30e5b94aa14f225f3704794d9429017ea9b461b0da

build:
  number: 0
  noarch: python

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - typing_extensions >=4
    - python >=${{ python_min }}
    - exceptiongroup >=1.0
    - packaging >=23.2
    - pathspec >=0.10.1
    - tomli >=1.2.2
tests:
  - python:
      imports:
        - scikit_build_core
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/
        - src/
        - pyproject.toml
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - python-build
        - cattrs >=22.2
        - cmake
        - hatch-vcs
        - hatchling
        - make
        - ninja
        - pip
        - pybind11
        - pytest >=7.0
        - pytest-subprocess
        - rich
        - setuptools
        - virtualenv
        - wheel
        - python ${{ python_min }}.*
    script:
      - pip check
      # test_requires_command can incorrectly report failure in 0.11.2
      - pytest -vv -m "not isolated" -k "not sdist_time_hash_set_epoch and not sdist_hash and not test_requires_command"

about:
  summary: Build backend for CMake based projects
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/scikit_build_core/resources/find_python/Copyright.txt
  homepage: https://pypi.org/project/scikit-build-core/

extra:
  recipe-maintainers:
    - conda-forge/scikit-build
    - henryiii
    - jcfr
    - thewtex
